### ISSUE TITLE
Corrigir dropdown de ordenação dos resultados de busca

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario-frontend#101]
A página de resultados de pesquisa oferece 3 opções de ordenamento dos resultados (relevância, mais recentes e mais antigos). Ao fazer uma pesquisa e escolher um ordenamento tudo funciona. Entretanto, ao fazer uma pesquisa em sequência, o botão do ordenamento não atualiza. 

Exemplo:
1ª busca: por "teste" em todas as cidades e todos os períodos. Ordenado por "mais recentes"  
https://queridodiario.ok.org.br/pesquisa?term=teste&sort_by=descending_date
Notar: a query no link está certa, o botão também e os resultados.
![image](https://user-images.githubusercontent.com/44185775/213280112-0fa67b3d-3485-4e1c-9a66-e2b93bb36acc.png)

2ª busca: foi trocado "teste" por "orçamento"
Notar: a query do link deixa de ter o ordenamento, os resultados também não estão ordenados por "mais recente" (tanto é que 2019 está antes de 2022), porém no **texto** do dropdown ainda indica que está ordenado.

![image](https://user-images.githubusercontent.com/44185775/213280253-532d16bd-6ce2-4a35-85a8-85370bda1db8.png)

Atualizar a página com F5 resolve o problema. O comportamento só aparece com buscas seguidas. 
A tarefa aqui seria corrigir para que o texto volte a ser "relevante" quando uma nova busca for feita.

**Comment by lguima** [comment]
Acho que esse problema está relacionado com o #158 

A causa raiz parece ser a redefinição dos filtros ao refazer uma busca (nem precisa trocar o termo).
