### ISSUE TITLE
Corrigir exibição de lista de cidades disponíveis

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario-frontend#102]
A página de cidades disponíveis (https://queridodiario.ok.org.br/cidades-disponiveis) exibe uma lista de cidades abaixo do painel de monitoramento. As cidades da lista são fornecidas pela API (https://queridodiario.ok.org.br/api/cities?levels=3) 
Entretanto, a lista está exibindo apenas parte das cidades (parando nas cidades começando com S) 
![image](https://user-images.githubusercontent.com/44185775/213287724-8a3255ea-b376-4bb6-911b-af29e0f956b0.png)

O comportamento só aparece na versão desktop. A mesma página pelo mobile exibe a lista toda com sucesso.

**Comment by tigreped** [comment]
Comportamento verificado e implementação aprovada para integração!

**Comment by trevineju** [comment]
Resolvido pelo #106
