### ISSUE TITLE
Painel do Looker Studio em /cidades-disponiveis não é exibido em navegadores chromium

### ISSUE THREAD

**Issue by guicalmeida** [okfn-brasil/querido-diario-frontend#105]
Em testes realizados no navegador Brave Versão 1.47.186 Chromium: 109.0.5414.119 e no Chrome Versão 109.0.5414.119 foi observado que o painel do Looker Studio não funciona:
![image](https://user-images.githubusercontent.com/60672629/217837484-d24e99b5-14cd-40fa-a9be-7396caf5938a.png)

Já no Firefox ele funciona, mas empurra a lista de cidades para além do fim do container, causando o problema relatado no issue #102

 Os testes foram feitos tanto em ambiente de desenvolvimento quanto no site em si, no Ubuntu 20.04.5

**EDIT: o erro foi causado por interação com uma extensão. desconsiderar este issue.**

**Comment by trevineju** [comment]
oi @guicalmeida. Obrigada pelos testes. 
Qual extensão causou o erro? Pode ser uma informação importante... 

Não sei qual resolução você viu a página, mas como o dashboard não é responsivo, nós optamos por configurar para que ele não apareça em telas menores.

**Comment by guicalmeida** [comment]
que vergonha, @trevineju! Foi isso mesmo. Eu estava a 10px do tamanho em que ele aparece - depois percebi o erro enquanto lia o código. Peço desculpas.
