### ISSUE TITLE
Filtro por período é apagado ao submeter a busca novamente

### ISSUE THREAD

**Issue by ogecece** [okfn-brasil/querido-diario-frontend#158]
### Passos para reproduzir

1. Acessar a página inicial
2. Realizar uma busca com termo e filtro por data
3. Na página de resultados, realizar a busca novamente

### Comportamento atual
Os valores do filtro por data são apagados.

### Comportamento esperado
Os valores do filtro por data devem permanecer os mesmos.

### Informações adicionais

[simplescreenrecorder-2023-07-14_17.35.36.webm](https://github.com/okfn-brasil/querido-diario-frontend/assets/26327506/c5be1c04-73c2-48d4-abbe-98683b19db2f)

**Comment by lguima** [comment]
Testando aqui, acontece também só de submeter a busca novamente, sem alterar o termo.
