### ISSUE TITLE
Filtro e ordenação são apagados ao submeter uma pesquisa novamente

### ISSUE THREAD

**Issue by lguima** [okfn-brasil/querido-diario-frontend#162]
### Passos para reproduzir

1. Acessar a página inicial
2. Realizar uma busca com **termo**, **cidade** e **período**
3. Na página de resultados, ordenar por "Mais recentes" ou "Mais antigos"
4. E então refazer a busca (acionar o botão "Pesquisar")

### Comportamento atual

O filtro de período e a ordenação são apagados.

### Comportamento esperado

O filtro de período e a ordenação devem permanecer inalterados.

## Busca inicial
![Captura de tela 2023-08-10 202157](https://github.com/okfn-brasil/querido-diario-frontend/assets/1562097/4a1bc8eb-a136-418e-abfe-c57b4318c121)

## Busca refeita
![Captura de tela 2023-08-10 202322](https://github.com/okfn-brasil/querido-diario-frontend/assets/1562097/c8b1faa8-355e-49d8-9b68-64f5c9b8114e)

---

- Resolve #101
- Resolve #158

**Comment by ddevdan** [comment]
Oi @lguima, tudo bem? Resolvi essa issue no PR #186. Podes marcar como hacktoberfest-accepted e revisar por favor? Obrigado :D
