### ISSUE TITLE
Atualizar versão em inglês do README.md

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario-frontend#180]
É necessário atualizar a tradução no README em inglês para corresponder ao atual estado do README em português. Os arquivos estão no diretório `docs`

**Comment by saiharsha-22** [comment]
Hello @trevineju can you assign this issue to me. I would like to work on this issue. I am participant of hacktoberfest 2023

**Comment by lguima** [comment]
Hi @saiharsha-22, thanks for contributing! 🎉 Please, go ahead! 🙏

**Comment by bmortella** [comment]
Olá, posso trabalhar nessa?

**Comment by ogecece** [comment]
Fica à vontade @bmortella !
