### ISSUE TITLE
Atualizar versão em inglês do CONTRIBUTING.md

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario-frontend#181]
É necessário atualizar a tradução no CONTRIBUTING em inglês para corresponder ao atual estado do CONTRIBUTING em português. Os arquivos estão no diretório `docs`

**Comment by saiharsha-22** [comment]
Hello @trevineju can you assign this issue to me. I would like to work on this issue. I am participant of hacktoberfest 2023
