### ISSUE TITLE
Atualizar número de cidades da plataforma na Home

### ISSUE THREAD

**Issue by tigreped** [okfn-brasil/querido-diario-frontend#194]
### Descrição

Buscar informação na API do QD e alterar o código para ficar de forma automatizada.

**Comment by lguima** [comment]
@tigreped temos a doc da API onde fornece essa informação?

**Comment by trevineju** [comment]
A [página de cidades disponíveis](https://queridodiario.ok.org.br/cidades-disponiveis) consome a API para listar as cidades do projeto. Talvez, ao invés de listar as cidades, basta fazer uma contagem delas. 

Os componentes da página estão no [módulo de pages do repositório](https://github.com/okfn-brasil/querido-diario-frontend/tree/main/src/app/modules/pages/available-cities). Parece ser possível aproveitar a lógica e fazer adaptações para modificar também a homepage.

**Comment by trevineju** [comment]
> @tigreped temos a doc da API onde fornece essa informação?

o endpoint dessa informação é: https://queridodiario.ok.org.br/api/cities?levels=3 (aí tem o problema é em forma de lista, não total. Precisa contabilizar o `lenght` disso de alguma forma

**Comment by AlexJBSilva** [comment]
> o endpoint dessa informação é: https://queridodiario.ok.org.br/api/cities?levels=3 (aí tem o problema é em forma de lista, não total. Precisa contabilizar o `lenght` disso de alguma forma

Qual seria o grau de dificuldade x tempo de implantação de se criar um novo endpoint no backend para entregar o número de cidades ao frontend?

(Desculpe estar perguntando sem olhar antes o frontend para entender se dá para **reutilizar** o retorno da chamada que lista as cidades para atualizar o número. Estou 'pegado' em outras missões no momento).

**Comment by EdimarioJr** [comment]
Fala galera, tudo bem? Posso pegar essa issue pra resolver?

**Comment by trevineju** [comment]
pode sim, @EdimarioJr!
