### ISSUE TITLE
Corrigir comportamento da página inicial de busca do QD Edu

### ISSUE THREAD

**Issue by tigreped** [okfn-brasil/querido-diario-frontend#195]
### Passos para reproduzir

Corrigir o gif que fica indicando a espera da carga da página inicial do QD Edu:

1. Substituir pela imagem estática do querido diário.

### Comportamento atual

Fica um gif estilo loading/carregando com um círculo laranja

### Comportamento esperado

Imagem estática indicando que o usuário pode realizar uma busca.

**Comment by AlexJBSilva** [comment]
Acredito que o **Comportamento esperado** ao iniciar a página de busca pode ser alcançado com um ajuste:
- **não alterar** `isLoading` para `true`  no trecho abaixo (adicionado no commit https://github.com/okfn-brasil/querido-diario-frontend/commit/ee2a4e6fd32cd044cf95c0e7d6e950ae26abc0cd):
https://github.com/okfn-brasil/querido-diario-frontend/blob/c1fb5d24a62e6bf7f5c37d2175106c77ae9c01a4/src/app/modules/pages/area-education/search/search.component.ts#L66-L67
