### ISSUE TITLE
Indicador das notificações desalinhado com o ícone

### ISSUE THREAD

**Issue by lguima** [okfn-brasil/querido-diario-frontend#197]
### Passos para reproduzir

1. Acessar a página inicial (Desktop)
2. Clicar no ícone de notificações

### Comportamento atual

- A seta indicadora das notificações está desalinhada com o ícone

### Comportamento esperado

- A seta indicadora das notificações deveria estar alinhada com o ícone

### Informações adicionais

![Captura de tela 2023-10-14 232838](https://github.com/okfn-brasil/querido-diario-frontend/assets/1562097/9bf45c1f-0123-4181-aff1-de263edec56e)

**Comment by camila-marquess** [comment]
oi, vou trabalhar nessa! =)

**Comment by maluojuara** [comment]
oie, vou dar seguimento a essa aqui, tá? (:

**Comment by ogecece** [comment]
Beleza @maluojuara !
