### ISSUE TITLE
Melhorar UX do campo Período

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario-frontend#20]
É necessPara fazer a busca por período é necessário digitar a data de inicio e de fim. Não está claro no formulário qual o formato da data (DD/MM/YYY por exemplo). Descobri ao acaso que se clicar na imagem ao lado desse campo de texto, aparece um calendário para facilitar esse preenchimento. Talvez ao clicar no campo de texto, abrir esse calendário já ajudasse a facilitar o uso desse campo. Também seria interessante limitar a data de fim para o ano atual (é possível eu colocar algo em 2050 se eu quiser pelo calendário), acredito que isso seja configurável de alguma maneira.

**Comment by giuliocc** [comment]
#75 corrigiu o clique mas a data de fim ainda fica pendente

**Comment by MoisesMsa** [comment]
Adicionei o limite do fim do campo, poderiam adicionar o label #hackotberfest-accept, por favor?
