### ISSUE TITLE
[Novo Post]: Lançamento do Diário do Clima

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario-frontend#201]
### Link do conteúdo

https://ok.org.br/noticia/organizacoes-lancam-plataforma-que-vai-monitorar-informacoes-sobre-clima-e-meio-ambiente-nos-diarios-oficiais/

### Número do post no site do Querido Diário

42

### Qual será a categoria dessa postagem?

Diário do Clima

### Caso haja imagens, insira-as aqui

Banner: https://querido-diario-static.nyc3.cdn.digitaloceanspaces.com/post0042/banner-post42.png

### Outros

O Diário do Clima é um produto que usa os dados do Querido Diário. Esse produto foi lançado e amplamente noticiado, porém ficou faltando adicionar essa notícia à memoria do Querido Diário, sendo que temos uma categoria para ele no blog. 

Essa tarefa envolve: 
- [ ] copiar o conteúdo do link acima para um arquivo `post-42.html`, formatá-lo e [adicionar ao repositório](https://github.com/okfn-brasil/querido-diario-frontend/tree/main/src/assets/pages/blogposts)
- [ ] adicionar um novo item no arquivo de [blog.json](https://github.com/okfn-brasil/querido-diario-frontend/blob/main/src/assets/pages/blog.json), seguindo o padrão do arquivo, para que a postagem apareça ordenada. 
ps.: notar que o número 42 foi pulado de propósito para encaixar esse material (:

**Comment by rasrbk** [comment]
quero fazer essa tarefa :)

**Comment by trevineju** [comment]
essa issue foi fechada pela PR #213
