### ISSUE TITLE
[Novo Post]: Querido Diário agora é um bem público digital

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario-frontend#202]
### Link do conteúdo

https://ok.org.br/noticia/querido-diario-e-aprovado-como-bem-publico-digital/

### Número do post no site do Querido Diário

46

### Qual será a categoria dessa postagem?

História

### Caso haja imagens, insira-as aqui

Banner: https://querido-diario-static.nyc3.cdn.digitaloceanspaces.com/post0046/banner-post46.png

### Outros

Essa tarefa envolve: 
- [ ] copiar o conteúdo do link acima para um arquivo `post-46.html`, formatá-lo e [adicionar ao repositório](https://github.com/okfn-brasil/querido-diario-frontend/tree/main/src/assets/pages/blogposts)
- [ ] adicionar um novo item no arquivo de [blog.json](https://github.com/okfn-brasil/querido-diario-frontend/blob/main/src/assets/pages/blog.json), seguindo o padrão do arquivo, para que a postagem apareça ordenada.

**Comment by gabrielliosc** [comment]
Gostaria de realizar essa issue pode atribuir à mim?

**Comment by rasrbk** [comment]
Oi, @gabrielliosc! obrigada por colaborar. atribuída :)
