### ISSUE TITLE
Problemas de formatação do Blog em iPhone

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario-frontend#204]
### Descrição

Duas pessoas usuárias da iPhone nos relataram alguns problemas na visualização do blog. 

Uma delas ainda informou que tentou navegar pelo blog com diferentes navegadores (Chrome, Safari e Firefox Focus) e confirmou o problema em todos.

![image](https://github.com/okfn-brasil/querido-diario-frontend/assets/44185775/50007551-611e-4a6c-ab27-b8fcc625b1bd)
![image](https://github.com/okfn-brasil/querido-diario-frontend/assets/44185775/527b388b-57e2-49f2-a1a2-d4ed54f8da44)

https://github.com/okfn-brasil/querido-diario-frontend/assets/44185775/153afa66-40e0-4784-808e-6183b820a5c5

**Comment by annezao** [comment]
Oie, tem alguém responsável por resolver esse bug? gostaria de ajudar.

**Comment by lguima** [comment]
oi, @annezao! ainda não tem ninguém responsável por esse bug, será ótimo se você puder ajudar! 😄

**Comment by maluojuara** [comment]
pessoal, será que essa issue ainda é pertinente? eu acabei de testar aqui no meu celular (iPhone) e aparentemente está funcionando normalmente. Seguem vídeo e prints em anexo:

![IMG_0397](https://github.com/user-attachments/assets/e0a3a157-feeb-4b31-b10c-3750a97c91fb)
![IMG_0398](https://github.com/user-attachments/assets/93d6f790-d110-48ad-9663-dba5f2009738)


https://github.com/user-attachments/assets/637dc8cc-f846-4e32-b72b-ee2668ab84a1

**Comment by ogecece** [comment]
Fechando a issue pois o problema parece estar resolvido!
