### ISSUE TITLE
Alinhamentos no header 

### ISSUE THREAD

**Issue by camila-marquess** [okfn-brasil/querido-diario-frontend#216]
### Passos para reproduzir

1. Abra no modo tablet;
2.  Clique em notificações

### Comportamento atual

Estando no modo tablet: 

1. O espaçamento na header desalinha e fica maior que a tela;
2.  É preciso arrastar para ver o resto dos componentes;
3.  Ao clicar no botão de notificações o retângulo desalinha;

### Comportamento esperado

1. Que não seja preciso arrastar a tela para ver o header completamente;
2. O botão de notificações deve ficar exatamente abaixo do sininho;
3. A caixa com notificações deve ficar completamente dentro da tela; 

### Informações adicionais

![image](https://github.com/okfn-brasil/querido-diario-frontend/assets/58270725/916092cf-4e8c-4622-bf4f-738e75d097c7)

![image](https://github.com/okfn-brasil/querido-diario-frontend/assets/58270725/87fc9221-ee25-4af5-b71c-546285142714)

**Comment by lguima** [comment]
oi, @camila-marquess, valeu por reportar o problema!

o posicionamento das notificações já está sendo tratado nessa issue: #197

**Comment by ogecece** [comment]
Fechando por duplicidade
