### ISSUE TITLE
Esboço de seção no site com formulário para produção de análises no QD-Edu

### ISSUE THREAD

**Issue by tigreped** [okfn-brasil/querido-diario-frontend#244]
### Descrição

Desenhar telas e especificar campos que seriam necessários para adicionar a seção e o formulário de solicitação de análises no QD-Edu.

**Comment by tigreped** [comment]
1) Adição de um link para Análises ao menu superior do QD EDU, além de "Busca" e "Sobre".
2) Adição de uma seção para as Análises na home do QD Edu
3) Página com o formulário para submissão

**Comment by tigreped** [comment]
1. e 2.
![home](https://github.com/okfn-brasil/querido-diario-frontend/assets/1479330/7f4d6651-bc01-42c3-8eea-f63f88389647)

**Comment by tigreped** [comment]
3.
![formulario](https://github.com/okfn-brasil/querido-diario-frontend/assets/1479330/1a065cdb-235a-4545-b34e-3dc3bd5f90de)

- Campos:

1. Nome
2. E-mail
3. Telefone
4. Palavras-chave
5. Descrição
6. Município
7. Período de tempo
8. Subtema
9. Envolvidos

**Comment by EdimarioJr** [comment]
Quais são seriam as opções e tipo dos campos Período de Tempo, Subtema e Envolvidos?

**Comment by EdimarioJr** [comment]
Os inputs estão também diferentes dos inputs da home. Esses inputs serão o novo padrão no design system?

**Comment by ogecece** [comment]
> Quais são seriam as opções e tipo dos campos Período de Tempo, Subtema e Envolvidos?

Se possível, reutiliza os componentes da [busca do QD-Edu](https://queridodiario.ok.org.br/educacao/busca). Pegar todos os subtemas e envolvidos automaticamente seria melhor.

Pro "período de tempo", se tiver como separar fácil as asbas do componente e só usar a "Intervalo de tempo" também seria melhor. Mas se não tiver como fazer fácil, é a vida. Vai como 1, 2, 3 e 4 mesmo se a pessoa escolher "1m", "2m", "3m" e "Tudo".

![image](https://github.com/okfn-brasil/querido-diario-frontend/assets/26327506/7bb2bbcb-ad06-491c-97c7-7889bcad163f)

> Os inputs estão também diferentes dos inputs da home. Esses inputs serão o novo padrão no design system?

Não, não. Foi desenhado com baixíssima fidelidade mesmo, só pra dar uma ideia de como seria. Inputs de exemplo a gente tem os da home, da busca do QD-Edu e da [página de sugestão](https://queridodiario.ok.org.br/sugestao). Diria que o mais próximo do QD-Edu seria melhor, mas todos esses não tem muitas diferenças entre si.

**Comment by EdimarioJr** [comment]
Funcionalidade sendo tratada no pr #263
