### ISSUE TITLE
Implementação de SEO para as páginas dos resultados das buscas no QD

### ISSUE THREAD

**Issue by tigreped** [okfn-brasil/querido-diario-frontend#253]
### Descrição

Implementar estratégias e técnicas de implementação de Search Engine Optimization baseadas no [levantamento realizado](https://docs.google.com/document/d/1qBlNGGkvI3NpUWkygxkDWdczVzdrAXN72eP0xOiIS08/edit#heading=h.1qz6njp1k3qr) de modo a permitir que motores de busca como o Google indexem o conteúdo do Querido Diário que for produzido através da interação dinâmica dos usuários com as pesquisas feitas gerando páginas de resultado que possam ser indexadas pelos motores.

**Comment by lguima** [comment]
fala @tigreped! qual foi o resultado que a gente conseguiu com essas mudanças?

**Comment by ogecece** [comment]
@lguima essas mudanças do PR #254 ainda não conseguiram ser capturadas por SEO, pois qualquer rota exceto a raíz retorna 404. A issue #258 foi criada por conta disso. Quer discutir por lá as melhores maneiras de solucionar?
