### ISSUE TITLE
Campo de cidade para de funcionar depois da primeira interação

### ISSUE THREAD

**Issue by lguima** [okfn-brasil/querido-diario-frontend#259]
### Passos para reproduzir

1. Abrir a página inicial com a barra de pesquisa
2. Começar a preencher o nome de uma cidade

### Comportamento atual

- O campo mostra sugestões de cidades
- Porém ao parar a digitação e retomar, as sugestões não são exibidas mais
- O mesmo comportamento acontece ao tirar ou acionar o foco no campo de cidade

### Comportamento esperado

- O campo deve mostrar sugestões de cidades após toda interação de digitação do campo
- E não deve ser afetado pelo foco no campo

### Informações adicionais

Navegador: Chrome (122.0.6261.128)

**Comment by MoisesMsa** [comment]
Opa, vou trabalhar nessa issue

**Comment by ogecece** [comment]
Issue atendida por #299
