### ISSUE TITLE
Aprimorar mensagem de limite máximo de resultados | Improve message when reaching results limit

### ISSUE THREAD

**Issue by campagnucci** [okfn-brasil/querido-diario-frontend#27]
_English version bellow._

Quando há muitos resultados, a API parece limitar a quantidade de resultados mostrados em 10 mil: 

![image](https://user-images.githubusercontent.com/2335525/142775320-32af0d76-4fd1-40d5-8f72-e7143db65f69.png)

Mas não há indicação para a pessoa usuária de que esse é um limite. A mensagem poderia ser mais informativa, com algo como: "Mais de 10 mil resultados encontrados" e abaixo "Tente buscar termos mais específicos ou usar mais de um termo para encontrar o que busca".

----

**ENGLISH**

When there are too many results, the API seems to limit the amount of results shown to 10,000:

![image](https://user-images.githubusercontent.com/2335525/142775320-32af0d76-4fd1-40d5-8f72-e7143db65f69.png)

But there is no indication to the user that this is a limit. The message could be more informative, with something like: "Mais de 10 mil resultados encontrados [Over 10,000 results found]" and below "Tente buscar termos mais específicos ou usar mais de um termo para encontrar o que busca [Try looking for more specific terms or use more than one term to find what you're looking for]".

**Comment by lguima** [comment]
oi, pessoal, puxei a #37 que resolve essa issue e fiz um ajuste na posição da mensagem, queria ver o que vocês acham:

# Busca
## Menor que o limite da API
### Desktop
![pesquisa-limite-resultados-menor-10000](https://user-images.githubusercontent.com/1562097/194726284-908751b2-461d-43cb-bfaf-4a4fedc5dfc2.png)

### Mobile
![pesquisa-limite-resultados-menor-10000-mobile](https://user-images.githubusercontent.com/1562097/194726427-59ebb95e-f28b-4e3d-a9d3-e00bfa5395fa.png)

## Maior ou igual que o limite da API
### Desktop
![pesquisa-limite-resultados-maior-igual-10000](https://user-images.githubusercontent.com/1562097/194726304-d5dc52d2-e44f-477d-9700-fd41780efcc8.png)

### Mobile
![pesquisa-limite-resultados-maior-igual-10000-mobile](https://user-images.githubusercontent.com/1562097/194726433-616a344d-d7f2-4a54-b9e9-5e4cfb57c500.png)

Preview: https://deploy-preview-37--querido-diario-plataforma.netlify.app/

cc: @giuliocc @trevineju @rennerocha @campagnucci

**Comment by lguima** [comment]
fala pessoal, poderiam opinar sobre a solução acima pra gente fechar esta issue?

**atual**
https://queridodiario.ok.org.br/pesquisa?term=covid

**solução**
https://deploy-preview-37--querido-diario-plataforma.netlify.app/pesquisa?term=covid

@giuliocc @trevineju @rennerocha @campagnucci

**Comment by trevineju** [comment]
@lguima a PR tá ótima, só deixei uma sugestão para o texto.
