### ISSUE TITLE
Atualizar número de cidades mapeadas pelo Censo na home

### ISSUE THREAD

**Issue by ArianeCamilo** [okfn-brasil/querido-diario-frontend#29]
A[ aba de andamento do censo](https://censo.ok.org.br/andamento/) informa que já temos 598 cidades mapeadas, então precisamos atualizar o número na home do site do Querido Diário.

![image](https://user-images.githubusercontent.com/32268301/150152255-911a3622-8f7a-4d71-9097-5c676024f405.png)

**Comment by lguima** [comment]
Não teria uma API pra gente usar pra atualizar esse número?

Já são 600 cidades agora hehe

**Comment by ArianeCamilo** [comment]
O número já foi atualizado. A issue pode ser fechada. 
Quanto à ideia do @lguima, podemos abrir uma nova issue voltada à API.
