### ISSUE TITLE
Problemas com nomes similares de cidades

### ISSUE THREAD

**Issue by kaiciasca** [okfn-brasil/querido-diario-frontend#3]
Primeiro de tudo, obrigada pelo lançamento da plataforma, de extrema importância para nós, pesquisadorxs da atuação pública, e interessades em geral.
Tive uma questão ao fazer uma pesquisa. Sou de Campinas-SP e, ao pesquisar a cidade, ela abre três possibilidades no campo do município (Campinas do Piauí, Campinas e Campinas do Sul). Selecionei "Campinas", que tem o nível 1 de abertura. Porém, ao pesquisar, o resultado vem como sendo sobre Campinas do Piauí, que tem nível 0 de abertura. Incluo um print aqui para verem como fica:
![print_querido diário](https://user-images.githubusercontent.com/87823190/126673897-b3b5560b-92ae-4445-8ee8-506622050e08.png)
Campinas do Piauí é a primeira cidade que aparece na lista de sugestões quando eu incluo o texto 'Campinas', porém eu chego a clicar e selecionar 'campinas' no campo. Ia até tentar propor o que poderia estar acontecendo, mas meus conhecimentos de programação são limitados, por enquanto, e queria mais passar o que estava ocorrendo mesmo.
Aproveitando o registro aqui, fiquei pensando se, na hora que surgem as possibilidades de município quando digito o nome da cidade no campo, seria legal aparecer também o estado, pq são diversas cidades com nomes iguais em diferentes estados no Brasil.

Registro aqui esses apontamentos que tive em email trocado com @giuliocc .

**Comment by giuliocc** [comment]
@kaiciasca obrigado novamente pelo apontamento detalhado e pela sugestão! :)

Só copiei a sugestão para a issue #5 pra ficarem separadas e mais fácil de monitorar.

**Comment by giuliocc** [comment]
Corrigido por 8b2f94a5. \o/
