### ISSUE TITLE
Campo de busca por município do QD Edu não funciona corretamente

### ISSUE THREAD

**Issue by maluojuara** [okfn-brasil/querido-diario-frontend#306]
### Passos para reproduzir

1. Acessar a página de busca da área "Educação" do QD (https://queridodiario.ok.org.br/educacao/busca);
2. Tentar digitar no campo de busca e ver que o funcionamento está bugado (placeholder está fora do local de digitar e o texto digitado aparece por cima do placeholder). 

OBS: Bug aconteceu principalmente no navegador Google Chrome

### Comportamento atual

https://github.com/user-attachments/assets/352a52a3-152d-46c6-b458-fa9174616478

### Comportamento esperado

Placeholder deveria desaparecer ao digitar e não deveria estar fora do campo de busca.

**Comment by ogecece** [comment]
Confirmo que aqui está com o mesmo problema apresentado no vídeo. Testei no Chrome e no Firefox
