### ISSUE TITLE
Adicionar funcionalidade para casos de sucesso / Add 'success stories' functionality

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario-frontend#33]
Criar uma seção na página "sobre" que possibilite a visualização de casos de sucesso (= conteúdos gerados com o Querido Diário a partir de parcerias, matérias jornalísticas, pesquisa acadêmica)

Essa funcionalidade já foi pensada desde o MVP do projeto e, portanto, já tem apêndice no código (conteúdo comentado ou não usado podem ser encontrados nos arquivos que tratam da página `about`) e só precisa da implementação de um carrossel ou algo do tipo pra funcionar.

------------------

Create a section on "about" page that allows the visualization of success stories (= content generated with Querido Diário from partnerships, journalistic articles, academic research)

This functionality has been thought of since the project's MVP and, therefore, already has an appendix in the code (commented or unused content can be found in the files related to `about` page) and only needs the implementation of a carousel or something like that to work.

**Comment by lguima** [comment]
Esta funcionalidade já está sendo trabalhada pela parceira Jurema.
