### ISSUE TITLE
Corrigir espaçamento da paginação | Fix pagination spacing

### ISSUE THREAD

**Issue by ArianeCamilo** [okfn-brasil/querido-diario-frontend#36]
### Português

Atualmente, temos um bug na área de paginação. Quando alguma busca atinge o limite e a paginação disponibiliza 1000 páginas, a seta da direita se sobrepõe ao número. Precisamos aumentar o espaçamento. Vale ressaltar que o mesmo não ocorre em dispositivos móveis.

![image](https://user-images.githubusercontent.com/32268301/164254189-9b64ad97-cf1d-49dd-b2ac-ae08f0f1feeb.png)
---
 
### English

We currently have a bug in the pagination area. When some search reaches the limit and the pagination makes 1000 pages available, the arrow on the right overlaps the number. We need to increase the spacing. It is worth mentioning that the same does not occur on mobile devices.

![image](https://user-images.githubusercontent.com/32268301/164254189-9b64ad97-cf1d-49dd-b2ac-ae08f0f1feeb.png)

**Comment by lguima** [comment]
Considerar utilizar o [TailwindCSS](https://tailwindcss.com/) adicionado na #46
