### ISSUE TITLE
Incluir âncora nos itens do glossário

### ISSUE THREAD

**Issue by nitaibezerra** [okfn-brasil/querido-diario-frontend#4]
Recomendo a inclusão de âncoras para os itens do glossário. Dessa forma será possível a criação de links que referencie um item específico, facilitando a navegação e o compartilhamento. Isso tornará o Glossário mais reutilizável, podendo se tornar uma base de referência linkável.

**Comment by giuliocc** [comment]
Finalizada por #13 :)

---

### English

Close by #13 :)
