### ISSUE TITLE
Atualizar "Contribua com código"

### ISSUE THREAD

**Issue by ArianeCamilo** [okfn-brasil/querido-diario-frontend#44]
Atualmente, o texto da seção "contribua com código" está linkando apenas o Github da OKBR, o que não contribui para que o usuário seja corretamente direcionado aos repositórios do Querido Diário. 
Sugiro uma edição no texto, listando os principais repositórios do projeto que aceitam contribuições (Raspadores, API, Toolbox, p. ex.).
![image](https://user-images.githubusercontent.com/32268301/166307874-c7fff3ea-c9da-46fd-bc00-a428fd5a606d.png)

**Comment by lguima** [comment]
PSC: Recentemente atualizamos a documentação do GitHub exatamente com essa informação:
- https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/.github/CONTRIBUTING.md

---

[**English**]

FYI: We recently updated the GitHub documentation with that exact information:
- https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/.github/CONTRIBUTING-en-US.md

**Comment by lguima** [comment]
@ArianeCamilo olhando com mais calma agora, vi que logo após a seção de "Contribua com código" já são listados alguns repositórios com os respectivos links:
- Processamento de dados
- Coleta de dados
- Censo
- Toolbox
- API pública
- Front end

Já foi feita a atualização que você sugeriu ou poderia explicar melhor, por favor?

---

[**English**]

@ArianeCamilo taking a close look I saw that below the "Contribua com código" section there is already a list of some of the repositories with their respective links:
- Processamento de dados
- Coleta de dados
- Censo
- Toolbox
- API pública
- Front end

Was your suggestion already applied or could you explain a little bit more, please?

![Captura de tela 2022-06-05 165535](https://user-images.githubusercontent.com/1562097/172068173-e7e81769-fd63-4866-88d0-698352085ac0.png)

**Comment by ArianeCamilo** [comment]
@lguima desculpe a demora, não tinha visto a notificação sobre suas perguntas. 
O apontamento está correto, os repositórios já estão listados, sim. Obrigada pela observação!
