### ISSUE TITLE
Incluir estado nos itens da lista de busca de cidades

### ISSUE THREAD

**Issue by giuliocc** [okfn-brasil/querido-diario-frontend#5]
Copiando aqui o comentário de @kaiciasca em #3 :

> Aproveitando o registro aqui, fiquei pensando se, na hora que surgem as possibilidades de município quando digito o nome da cidade no campo, seria legal aparecer também o estado, pq são diversas cidades com nomes iguais em diferentes estados no Brasil.

**Comment by barraponto** [comment]
Parece resolvido:
<img width="756" alt="Screen Shot 2021-09-08 at 15 01 50" src="https://user-images.githubusercontent.com/134005/132561046-8d39a92a-4ec9-43af-8e0b-7a1bbe7e96cd.png">

**Comment by giuliocc** [comment]
Corrigido por: 1e46556b4182655d2438ad4a1e034f82e29a4a2c

\o/
