### ISSUE TITLE
Adicionar visualização de dados com mapa na página inicial

### ISSUE THREAD

**Issue by tigreped** [okfn-brasil/querido-diario-frontend#7]
Adicionar um mapa à página inicial do Querido Diário, na sessão "Acompanhe a evolução do Querido Diário", indicando visualmente todos os municípios, com destaque para as capitais, que pode constar com um mecanismo de luzes que vão acendendo e mudando de cor de acordo com o nível de libertação dos Diários Oficiais daquele município, de acordo com a narrativa atual:

Ex.:

Nível 0 - Apagada - O diário ainda não está cadastrado na plataforma (censo)
Nível 1 - Vermelha - O diário foi cadastrado no censo, mas não tem raspador implementado
Nível 2 - Amarela - O raspador está pronto, mas falta extrair o texto do arquivo fechado
Nível 3 - Verde - O conteúdo está disponibilizado em formato original e em .TXT

Ou algum tipo análogo de visualização, com fogueiras ou outro símbolo/cores.

Obs.: idealmente essas informações sobre o status do censo e dos raspadores deveriam ser consumidas a partir de uma API.

**Comment by dadosabertossergipe** [comment]
Desenvolvi alguns mapas utilizando D3.js direto no `ObservableHQ` (um "Jupyter Notebook" para visualização). Os mapas construídos lá podem ser facilmente integrados com diferentes páginas HTML. Mais na frente detalho como essa integração pode ser feita diretamente pelo notebook. 

A proposta é dar andamento a discussão que começou lá no Discord no canal do censo. Não tenho muito conhecimento sobre Angular então, como sugestão, estou atualizando essa Issue para que possamos discutir qual a melhor forma de trazer isso para o site do QD e também para ver se alguém com melhor conhecimento do Angular pode me ajudar nisso. 

A seguir mostro um pouco da integração direta do `ObservableHQ`. Para não ficar muito grande essa resposta, atualizei o notebook: https://observablehq.com/@adolfoguimaraes/br-queridodiario-mapa, com mais informações sobre o que foi produzido e como podemos incorporar. 

O código produzido pode ser acessado direto no notebook e lá explico cada parte, caso a solução seja incorporar diretamente o código D3.js produzido. 

## Integrando o notebook direto no site: 

O `ObservableHQ` permite algumas formas *embed* das visualiações criadas: 

### **1 - Usando iframe:**

Seleciono quais células quero que sejam incorporadas e ele gera o código para incorporar na página HTML.

**Código Gerado**

```html
<iframe width="100%" height="1656" frameborder="0"
  src="https://observablehq.com/embed/@adolfoguimaraes/br-queridodiario-mapa?cells=viewof+search%2Cviewof+table%2Cchart%2Cviewof+select%2Cchart_state"></iframe>
```

No link a seguir, criei um exemplo incorporando na página HTML:

https://jsfiddle.net/adolfoguimaraes/dwxv7zf5/


### **2 - Usando JavaScript**

Outra forma é incorporara utilizando código javascript. Basicamente ele cria um script com as importações e na página basta criar os divs correspondentes. Desta forma é possível personalizar as divs de acordo com o site, diferente do iFrame que não temos opção de personalização. 

**HTML**

```html
<div id="observablehq-viewof-search-48090f8d"></div>
<div id="observablehq-viewof-table-48090f8d"></div>
<div id="observablehq-chart-48090f8d"></div>
<div id="observablehq-viewof-select-48090f8d"></div>
<div id="observablehq-chart_state-48090f8d"></div>
```

**Javascript**

```javascript
import {Runtime, Inspector} from "https://cdn.jsdelivr.net/npm/@observablehq/runtime@4/dist/runtime.js";
import define from "https://api.observablehq.com/@adolfoguimaraes/br-queridodiario-mapa.js?v=3";
new Runtime().module(define, name => {
  if (name === "viewof search") return new Inspector(document.querySelector("#observablehq-viewof-search-48090f8d"));
  if (name === "viewof table") return new Inspector(document.querySelector("#observablehq-viewof-table-48090f8d"));
  if (name === "chart") return new Inspector(document.querySelector("#observablehq-chart-48090f8d"));
  if (name === "viewof select") return new Inspector(document.querySelector("#observablehq-viewof-select-48090f8d"));
  if (name === "chart_state") return new Inspector(document.querySelector("#observablehq-chart_state-48090f8d"));
  return ["br_map_filter","br_state_filter"].includes(name);
});
```


Uma terceira forma de incorporar é a partir do uso do React. A partir da instalação de uns pacotes do Observable é possível importar os componentes direto no site. Ainda não testei esse tipo de incorporação. 

**Bom, qualquer uma dessas opções de `embed` fica "presa" ao notebook. Apesar de ser uma plataforma pública e colaborativa, pode fugir um pouco do fluxo de manutenção do site. De qualquer forma, pode ser um primeiro passo para uma solução futura mais integrada ao site e a estrutura do QD**.

Como falei anteriormente, uma explicação mais detalhada do que foi produzido está no notebook: https://observablehq.com/@adolfoguimaraes/br-queridodiario-mapa na seção **Informações para incorporar este código**.

**Comment by lguima** [comment]
Acho muito válido ter essa informação visual, só não acho que é o caso de ficar na página inicial, talvez em `/cidades-disponiveis`.

**Comment by ogecece** [comment]
Galera, estou fechando a issue entendendo que o [painel de cobertura](https://queridodiario.ok.org.br/cidades-disponiveis) já atende os requisitos
