### ISSUE TITLE
Adicionar visualização de dados com gráficos à página inicial

### ISSUE THREAD

**Issue by tigreped** [okfn-brasil/querido-diario-frontend#8]
Na sessão "Acompanhe a evolução do Querido Diário", adicionar gráficos (tipo pizza, barra, linha, etc.) indicando visualmente as estatísticas com foco no recorte do status atual, organizando a porcentagem concluída com relação aos totais por municípios, por estados, por capitais, por regiões.

Nível 0 - O diário ainda não está cadastrado na plataforma (censo)
Nível 1 - O diário foi cadastrado no censo, mas não tem raspador implementado
Nível 2 - O raspador está pronto, mas falta extrair o texto do arquivo fechado
Nível 3 - O conteúdo está disponibilizado em formato original e em .TXT

Por ex.:

12 cidades já na plataforma (Nível 3)
12/27 Capitais (44%)
12/ 5570 Municípios (0,21%)
X/ 27 Estados (Y%)

2226 cidades já tem robôs para coletar diário (Nível 2)
12/27 Capitais (44%)
2226/5570 (39,96%) Municípios
Z/27 (W%) Estados

597 cidades já foram mapeadas pelo senso (Nível 1)
12/27 Capitais (44%)
2226/5570 (39,96%) Municípios
x/27 (y%) Estados

Ou ainda, utilizar agrupamentos de estatísticas por regiões:
Centro-Oeste
Nordeste
Norte
Sudeste
Sul

Obs.: idealmente essas informações sobre o status do censo e dos raspadores deveriam ser consumidas a partir de uma API.

**Comment by lguima** [comment]
Acho muito válido ter essa informação visual, só não acho que é o caso de ficar na página inicial, talvez em `/cidades-disponiveis`.

**Comment by ogecece** [comment]
Entendo o [painel de cobertura](https://queridodiario.ok.org.br/cidades-disponiveis) atende quase completamente os requisitos e podemos fechar a issue
