### ISSUE TITLE
Aviso de depreciação da build do Netlify

### ISSUE THREAD

**Issue by lguima** [okfn-brasil/querido-diario-frontend#86]
Precisamos atualizar a build do Netlify, a que usamos atualmente vai deixar de funcionar a partir de **15 de Novembro** de 2022.

> DEPRECATION NOTICE: Builds using the Xenial build image will fail after November 15th, 2022.
> 
> The build image for this site uses Ubuntu 16.04 Xenial Xerus, which is no longer supported.
> All Netlify builds using the Xenial build image will begin failing in the week of November 15th, 2022.
> 
> To avoid service disruption, please select a newer build image at the following link:
> https://app.netlify.com/sites/querido-diario-plataforma/settings/deploys#build-image-selection
> 
> For more details, visit the build image migration guide:
> https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239

cc: @giuliocc

**Comment by giuliocc** [comment]
@lguima atualizei aqui e executei um novo build. Aparentemente não deu problemas. Fechamos a issue?
